spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springschoolapp
    username: bakemono
    password: bakemono
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
